# Generated by Django 5.2.7 on 2025-10-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='uploads/')),
                ('sketch_image', models.ImageField(blank=True, null=True, upload_to='sketches/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
